/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://c62sgj6t2zbfvamjyq3vaq3ipe.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ujf66fdieve37ci26ikoak7qny",
    "aws_cognito_identity_pool_id": "ap-southeast-1:77e498c1-3915-4c18-bb8f-b8fc08b2c719",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_v1cFYmAy0",
    "aws_user_pools_web_client_id": "4q24d2as4bm4kol3qi2u751ppc",
    "oauth": {}
};


export default awsmobile;
